name: 🚀 新功能建议
description: 提出一个新的功能
body:
  - type: markdown
    attributes:
      value: 感谢你关注这个项目并花时间填写这个功能报告！
  - type: textarea
    id: feature-description
    attributes:
      label: 对问题的清晰和简明的描述
      description: 作为一个使用 [项目] 的开发者，我想要 [目标/愿望]，以便 [受益]。我打算为这个问题提交一个 PR。谢谢！
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: 推荐的解决方案
      description: 在模块 [xy] 中我们可以提供以下实现……
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: 替代方案
      description: 清晰而简明地描述你考虑过的任何替代解决方案或功能。
  - type: textarea
    id: additional-context
    attributes:
      label: 额外上下文
      description: 关于该功能请求的任何其他背景或截图。
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 检查
      description: 在提交问题之前，请确保你做到以下几点
      options:
        - label: 遵循 [行为准则](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
          required: true
        - label: 检查是否已经有一个要求相同功能的问题，以避免重复创建。
          required: true
